PerformanceMVCCore/Controllers/AvaliacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DALCore.Models;
using Microsoft.AspNetCore.Http;

namespace PerformanceMVCCore.Controllers
{
    public class AvaliacoesController : Controller
    {
        private readonly PerformanceContext _context;

        public AvaliacoesController(PerformanceContext context)
        {
            _context = context;
        }

        // GET: Avaliacoes
        public async Task<IActionResult> Index()
        {
			ViewBag.Current = "IndexAvaliacoes";

			var performanceContext = _context.Avaliacoes.Include(a => a.IdAvaliadorNavigation).Include(a => a.IdClassificacaoNavigation).Include(a => a.IdProjetoNavigation).Include(a => a.IdUtilizadorNavigation);
            return View(await performanceContext.ToListAsync());
        }

        // GET: Avaliacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
			ViewBag.Current = "IndexAvaliacoes";

			if (id == null)
            {
                return NotFound();
            }

            var avaliacoes = await _context.Avaliacoes
                .Include(a => a.IdAvaliadorNavigation)
                .Include(a => a.IdClassificacaoNavigation)
                .Include(a => a.IdProjetoNavigation)
                .Include(a => a.IdUtilizadorNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avaliacoes == null)
            {
                return NotFound();
            }

            return View(avaliacoes);
        }

        // GET: Avaliacoes/Create
        public IActionResult Create()
        {
			ViewBag.Current = "IndexAvaliacoes";

			ViewData["IdAvaliador"] = new SelectList(_context.Utilizadores, "Id", "Nome");
            ViewData["IdClassificacao"] = new SelectList(_context.Classificacoes, "Id", "Nota");
            ViewData["IdProjeto"] = new SelectList(_context.Projetos, "Id", "Nome");
			ViewData["AvColaborador"] = new SelectList(_context.Utilizadores.Where(x => x.IdFuncao == 4), "Id", "Nome");
			ViewData["AvGestor"] = new SelectList(_context.Utilizadores.Where(x => x.IdFuncao == 5), "Id", "Nome");
			return View();
        }

        // POST: Avaliacoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdClassificacao,IdUtilizador,IdAvaliador,IdProjeto,Estado,Mes,Ano,PontosFortes,PontosFracos,Active,DataCriacao,DataEdicao")] Avaliacoes avaliacoes, string avfuncao, int colaboradorAv, int gestorAv)
		{

			if (ModelState.IsValid)
            {
				// Passa o valor submetida ao estado da avaliação
				avaliacoes.Estado = "Submetida";

				//Passa o Id da pessoa que está logada ao IdAvaliador (o avaliador fica automático, ou seja, o avaliador é a pessoa que fez login)
				String User = HttpContext.Session.GetString("MySession");
				avaliacoes.IdAvaliador = _context.Utilizadores.Where(x => x.Username == User).FirstOrDefault().Id;

				//Passa o valor para o IdUtilizador (pessoa avaliada). Filtra os utilizadores que vão ser avaliados dos que não vão
				if (avfuncao == "Colaborador")
				{
					avaliacoes.IdUtilizador = colaboradorAv;
				}
				if (avfuncao == "Gestor de Projeto")
				{
					avaliacoes.IdUtilizador = gestorAv;
				}
				

				//Para atualizar automaticamente para a data e hora atuais
				avaliacoes.DataCriacao = DateTime.Now;
                avaliacoes.DataEdicao = DateTime.Now;

                _context.Add(avaliacoes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAvaliador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdAvaliador);
            ViewData["IdClassificacao"] = new SelectList(_context.Classificacoes, "Id", "Nota", avaliacoes.IdClassificacao);
            ViewData["IdProjeto"] = new SelectList(_context.Projetos, "Id", "Nome", avaliacoes.IdProjeto);
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdUtilizador);
            return View(avaliacoes);
        }

        // GET: Avaliacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
			ViewBag.Current = "IndexAvaliacoes";

			if (id == null)
            {
                return NotFound();
            }

            var avaliacoes = await _context.Avaliacoes.FindAsync(id);
            if (avaliacoes == null)
            {
                return NotFound();
            }
            ViewData["IdAvaliador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdAvaliador);
            ViewData["IdClassificacao"] = new SelectList(_context.Classificacoes, "Id", "Nota", avaliacoes.IdClassificacao);
            ViewData["IdProjeto"] = new SelectList(_context.Projetos, "Id", "Nome", avaliacoes.IdProjeto);
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdUtilizador);
            return View(avaliacoes);
        }

        // POST: Avaliacoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdClassificacao,IdUtilizador,IdAvaliador,IdProjeto,Estado,Mes,Ano,PontosFortes,PontosFracos,Active,DataCriacao,DataEdicao")] Avaliacoes avaliacoes)
        {
            if (id != avaliacoes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Para atualizar automaticamente para a data e hora atuais
                    avaliacoes.DataEdicao = DateTime.Now;

                    _context.Update(avaliacoes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvaliacoesExists(avaliacoes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAvaliador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdAvaliador);
            ViewData["IdClassificacao"] = new SelectList(_context.Classificacoes, "Id", "Nota", avaliacoes.IdClassificacao);
            ViewData["IdProjeto"] = new SelectList(_context.Projetos, "Id", "Nome", avaliacoes.IdProjeto);
            ViewData["IdUtilizador"] = new SelectList(_context.Utilizadores, "Id", "Nome", avaliacoes.IdUtilizador);
            return View(avaliacoes);
        }

        // GET: Avaliacoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
			ViewBag.Current = "IndexAvaliacoes";

			if (id == null)
            {
                return NotFound();
            }

            var avaliacoes = await _context.Avaliacoes
                .Include(a => a.IdAvaliadorNavigation)
                .Include(a => a.IdClassificacaoNavigation)
                .Include(a => a.IdProjetoNavigation)
                .Include(a => a.IdUtilizadorNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avaliacoes == null)
            {
                return NotFound();
            }

            return View(avaliacoes);
        }

        // POST: Avaliacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var avaliacoes = await _context.Avaliacoes.FindAsync(id);
            _context.Avaliacoes.Remove(avaliacoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvaliacoesExists(int id)
        {
            return _context.Avaliacoes.Any(e => e.Id == id);
        }
    }
}

PerformanceMVCCore/Controllers/NotificacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DALCore.Models;

namespace PerformanceMVCCore.Controllers
{
    public class NotificacoesController : Controller
    {
        private readonly PerformanceContext _context;

        public NotificacoesController(PerformanceContext context)
        {
            _context = context;
        }

        // GET: Notificacoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Notificacoes.ToListAsync());
        }

        // GET: Notificacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notificacoes = await _context.Notificacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notificacoes == null)
            {
                return NotFound();
            }

            return View(notificacoes);
        }

        // GET: Notificacoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notificacoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,TipoNotificacao,TipoDestinatario,Destinatario,Dia,Subject,Body,Parametros,Active,DataCriacao,DataEdicao,UserCriacao,UserEdicao")] Notificacoes notificacoes)
        {
            if (ModelState.IsValid)
            {
                //Para atualizar automaticamente para a data e hora atuais
                notificacoes.DataCriacao = DateTime.Now;
                notificacoes.DataEdicao = DateTime.Now;

                _context.Add(notificacoes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(notificacoes);
        }

        // GET: Notificacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notificacoes = await _context.Notificacoes.FindAsync(id);
            if (notificacoes == null)
            {
                return NotFound();
            }
            return View(notificacoes);
        }

        // POST: Notificacoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,TipoNotificacao,TipoDestinatario,Destinatario,Dia,Subject,Body,Parametros,Active,DataCriacao,DataEdicao,UserCriacao,UserEdicao")] Notificacoes notificacoes)
        {
            if (id != notificacoes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Para atualizar automaticamente para a data e hora atuais
                    notificacoes.DataEdicao = DateTime.Now;

                    _context.Update(notificacoes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotificacoesExists(notificacoes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(notificacoes);
        }

        // GET: Notificacoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notificacoes = await _context.Notificacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notificacoes == null)
            {
                return NotFound();
            }

            return View(notificacoes);
        }

        // POST: Notificacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var notificacoes = await _context.Notificacoes.FindAsync(id);
            _context.Notificacoes.Remove(notificacoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotificacoesExists(int id)
        {
            return _context.Notificacoes.Any(e => e.Id == id);
        }
    }
}

PerformanceMVCCore/Views/Shared/WorkInProgress.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";

}

@{
	ViewData["Title"] = "WorkInProgress";
}


<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>work in progress</title>

</head>
<style>
	body {
		background-color: white;
	}
	.GifContainer {
		width: 100%;
		text-align:center;
	}
	img {
		width: 55%;
	}
</style>


<div class="GifContainer">

		<img src="~/images/3jnq.gif" >
</div>

</html>

PerformanceMVCCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - PerformanceMVCCore</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/Tabelas.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

	</environment>

</head>
<body>


	<style>
		#imgLogo {
			max-width: 120px;
			width: auto;
		}

		.navbar {
			background-color: lightgrey;
		}

		footer {
			margin: 20px;
			text-align: right;
		}

		#navLogin {
			float: right;
			color: white;
			margin-top: 15px;
			color: darkred;
		}

		#navPrincipal {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
		}

		li {
			float: left;
			font-size: 16px;
			font-weight: bold;
		}

		.active {
			display: block;
			color: black;
			text-align: center;
			padding: 16px;
			text-decoration: none;
		}

		li a {
			display: block;
			color: darkred;
			text-align: center;
			padding: 16px;
			text-decoration: none;
		}




			li a:hover {
				color: black;
				text-decoration: none;
			}
		#linkNotificacoes {
			color: black;
		}
	</style>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
					<img id="imgLogo" src="~/images/bannerlogo.png" />


				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul id="navLogin" class="nav navbar-nav">
					<p>
						@*Welcome*@ @Context.Session.GetString("MySession")
						<a id="linkLogout" asp-controller="Login" asp-action="Logout">
							&nbsp; Logout
							<i class="fas fa-door-open">
							<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous"></i>
						</a> &nbsp; &nbsp;
						<a asp-controller="Notificacoes" asp-action="Index" id="linkNotificacoes" title="Notificações">
							<i class="far fa-bell">
								<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
							</i>
						</a>
					</p>
				</ul>
				<ul id="navPrincipal">

					<li class="">@Html.ActionLink("Utilizadores", "Index", "Utilizadores", null, new { @class = ViewBag.Current == "IndexUtilizadores" ? "active" : "" })</li>

					<li class="">@Html.ActionLink("Projetos", "Index", "Projetos", null, new { @class = ViewBag.Current == "IndexProjetos" ? "active" : "" })</li>

					<li class="">@Html.ActionLink("Clientes", "Index", "Clientes", null, new { @class = ViewBag.Current == "IndexClientes" ? "active" : "" })</li>
					<li class="">@Html.ActionLink("Avaliações", "Index", "Avaliacoes", null, new { @class = ViewBag.Current == "IndexAvaliacoes" ? "active" : "" })</li>
					<li class="">@Html.ActionLink("Classificações", "Index", "Classificacoes", null, new { @class = ViewBag.Current == "IndexClassificacoes" ? "active" : "" })</li>
					<li class="">@Html.ActionLink("Dashboards", "Index", "Dashboards", null, new { @class = ViewBag.Current == "IndexDashboards" ? "active" : "" })</li>

				</ul>

			</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />

	<div class="container body-content">
		@RenderBody()
	</div>
	<footer>
		<p>&copy; 2018 -  WINNING Scientific Management</p>
	</footer>


	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)

</body>
</html>